ifeq ($(CONFIG_TRUSTONIC_TEE_SUPPORT),y)
    $(info "CONFIG_MTK_PLATFORM: $(CONFIG_MTK_PLATFORM)")
    $(info "CONFIG_TRUSTONIC_TEE_VERSION: $(CONFIG_TRUSTONIC_TEE_VERSION)")
    ccflags-y += -I$(srctree)/drivers/misc/mediatek/gud/$(CONFIG_TRUSTONIC_TEE_VERSION)/MobiCoreDriver/public
    ccflags-y += -I$(srctree)/drivers/misc/mediatek/gud/$(CONFIG_TRUSTONIC_TEE_VERSION)/MobiCoreDriver/public/GP
endif
